<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<robot name="hunter_v1" 
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="wheelbase" value="0.64857" />
    <xacro:property name="track" value="0.56" />
    <xacro:property name="wheel_vertical_offset" value="-0.0165" />
    <xacro:property name="wheel_steering_offset" value="0.06" />

    <xacro:property name="wheel_length" value="1.1653e-01" />
    <xacro:property name="wheel_radius" value="1.6459e-01" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/base_link.dae" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="0 0 0.12" rpy="0 0 0" />
            <geometry>
                <box size="0.75 0.15 0.08"/>
            </geometry>
        </visual>
        <visual>
            <origin xyz="0.17 0 0.06" rpy="0 0 0" />
            <geometry>
                <box size="0.45 0.37 0.18"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.29 0 0.05" rpy="0 0 0" />
            <geometry>
                <box size="0.25 0.38 0.26"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="-0.1 0 0.07" rpy="0 0 0" />
            <geometry>
                <box size="0.56 0.38 0.22"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="40" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <!-- front right wheel -->
    <joint name="front_right_steering" type="revolute">
        <origin xyz="-${wheelbase/2} ${track/2-wheel_steering_offset} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="front_right_steer_link"/>
        <axis xyz="0 0 1" rpy="0 0 0" />
        <limit lower="-0.785" upper="0.785" effort="20" velocity="0.8" />
    </joint>

    <link name="front_right_steer_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin xyz="0 ${wheel_steering_offset} 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/steer_conn_fr.dae" />
            </geometry>
        </visual>
    </link>

    <joint name="front_right_wheel" type="continuous">
        <origin xyz="0 ${wheel_steering_offset} 0" rpy="0 0 0" />
        <parent link="front_right_steer_link"/>
        <child link="front_right_wheel_link"/>
        <axis xyz="0 -1 0" rpy="0 0 0" />
    </joint>

    <link name="front_right_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/wheel_fr.dae" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/hub_shape.stl" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
    </link>

    <!-- front left wheel -->
    <joint name="front_left_steering" type="revolute">
        <origin xyz="-${wheelbase/2} -${track/2-wheel_steering_offset} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="front_left_steer_link"/>
        <axis xyz="0 0 1" rpy="0 0 0" />
        <limit lower="-0.785" upper="0.785" effort="20" velocity="0.8" />
    </joint>

    <link name="front_left_steer_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin xyz="0 -${wheel_steering_offset} 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/steer_conn_fl.dae" />
            </geometry>
        </visual>
    </link>

    <joint name="front_left_wheel" type="continuous">
        <origin xyz="0 -${wheel_steering_offset} 0" rpy="0 0 0" />
        <parent link="front_left_steer_link"/>
        <child link="front_left_wheel_link"/>
        <axis xyz="0 -1 0" rpy="0 0 0" />
    </joint>

    <link name="front_left_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/wheel_fl.dae" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 3.14" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/hub_shape.stl" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
    </link>

    <!-- rear left wheel -->
    <link name="rear_left_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/wheel_rl.dae" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 3.14" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/hub_shape.stl" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
    </link>

    <joint name="rear_left_wheel" type="continuous">
        <origin xyz="${wheelbase/2} -${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <axis xyz="0 -1 0" rpy="0 0 0" />
    </joint>

    <!-- rear right wheel -->
    <link name="rear_right_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/wheel_rr.dae" />
            </geometry>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/hub_shape.stl" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
        </collision>
    </link>

    <joint name="rear_right_wheel" type="continuous">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <axis xyz="0 -1 0" rpy="0 0 0" />
    </joint>
</robot>
